Repository polygolf-lang/polygolf, pull requests merged in 2023-12, with the labels that each got.

#270 Add noEmit flag for testing
  src/cli.ts
  src/common/Language.ts
  src/common/compile.ts
  src/interpreter/index.ts
  src/markdown-tests/index.ts
Labels: enhancement, architecture

#293 Add shorthand `$x +<- 1;` for `$x <- ($x + 1);`
  README.md
  src/frontend/lexer.ts
  src/frontend/parse.ts
Labels: enhancement

#254 Nim function calls
  src/frontend/parse.ts
  src/languages/nim/emit.ts
  src/languages/nim/index.ts
  src/languages/nim/nim.test.md
  src/languages/nim/plugins.ts
  src/programs/code.golf-default.test.md
Labels: enhancement, plugin

#276 Split & merge prints
  src/IR/assignments.ts
  src/common/Spine.ts
  src/languages/golfscript/index.ts
  src/languages/lua/index.ts
  src/languages/nim/index.ts
  src/languages/swift/index.ts
  src/plugins/block.ts
  src/plugins/print.test.md
  src/plugins/print.ts
Labels: enhancement, plugin

#300 [WIP] Janet
  src/languages/golfscript/index.ts
  src/languages/janet/emit.ts
  src/languages/janet/index.ts
  src/languages/janet/janet.test.md
  src/languages/janet/plugins.ts
  src/languages/javascript/index.ts
  src/languages/languages.ts
  src/languages/lua/index.ts
  src/languages/nim/index.ts
  src/languages/python/index.ts
  src/languages/swift/index.ts
  src/plugins/arithmetic.ts
  src/plugins/ops.ts
  src/plugins/print.test.md
  src/plugins/print.ts
Labels: enhancement, newlang
