Repository polygolf-lang/polygolf, pull requests merged in 2023-02, with the labels that each got.

#72 make *.test.md linguist-detectable
  .gitattributes
Labels: bug

#77 Fix #36
  src/IR/types.ts
  src/languages/lua/index.ts
  src/languages/nim/index.ts
  src/plugins/types.ts
Labels: bug

#53 Add Swift
  src/cli.ts
  src/languages/languages.ts
  src/languages/swift/emit.ts
  src/languages/swift/index.ts
  src/languages/swift/plugins.ts
  src/languages/swift/swift.test.md
Labels: newlang

#60 Allow emitters to return trees of tokens instead of arrays
  src/common/Language.ts
  src/common/emit.ts
  src/languages/lua/emit.ts
  src/languages/nim/emit.ts
  src/languages/polygolf/emit.ts
  src/languages/python/emit.ts
  src/markdown-tests/build.ts
Labels: enhancement

#58 Add GolfScript
  src/cli.ts
  src/languages/golfscript/emit.ts
  src/languages/golfscript/golfscript.test.md
  src/languages/golfscript/index.ts
  src/languages/golfscript/plugins.ts
  src/languages/languages.ts
Labels: newlang

#75 Fix #55
  src/languages/polygolf/emit.ts
Labels: bug

#76 Fix #69
  tsconfig.json
Labels: bug

#80 Fix #54
  src/common/Language.ts
  src/languages/python/index.ts
  src/plugins/ops.ts
Labels: bug

#109 Add finiteFlatten function
  src/common/Language.ts
Labels: enhancement

#108 Swift bugfixes
  src/languages/swift/emit.ts
  src/languages/swift/index.ts
  src/languages/swift/swift.test.md
Labels: bug

#107 Python bugfixes
  src/languages/python/emit.ts
  src/languages/python/index.ts
  src/languages/python/python.test.md
  src/plugins/idents.ts
Labels: bug

#131 Swift and Golfscript
  src/languages/golfscript/index.ts
  src/languages/swift/index.ts
Labels: enhancement

#86 add equalityToInequality plugin
  src/languages/golfscript/index.ts
  src/languages/lua/index.ts
  src/languages/nim/index.ts
  src/languages/python/index.ts
  src/languages/python/python.test.md
  src/languages/swift/index.ts
  src/plugins/ops.test.md
  src/plugins/ops.ts
Labels: enhancement

#130 Emit error
  src/common/applyLanguage.ts
  src/common/emit.ts
  src/languages/golfscript/emit.ts
  src/languages/lua/emit.ts
  src/languages/nim/emit.ts
  src/languages/python/emit.ts
  src/languages/swift/emit.ts
Labels: enhancement

#74 Rewrite Lua tests as Markdown tests
  src/frontend/parse.ts
  src/languages/lua/emit.ts
  src/languages/lua/index.ts
  src/languages/lua/lua.test.md
  src/languages/lua/lua.test.ts
Labels: enhancement

#82 Fix #44
  src/common/Language.ts
  src/languages/nim/emit.ts
  src/languages/nim/index.ts
  src/languages/nim/nim.test.md
Labels: bug

#64 Packing
  src/cli.ts
  src/common/Language.ts
  src/common/applyLanguage.ts
  src/languages/nim/index.ts
  src/languages/python/emit.ts
  src/languages/python/index.ts
  src/plugins/packing.ts
Labels: enhancement

#121 For argv node
  src/IR/IR.ts
  src/IR/loops.ts
  src/IR/opcodes.ts
  src/IR/toplevel.ts
  src/common/getType.ts
  src/common/symbols.ts
  src/frontend/lexer.ts
  src/frontend/parse.ts
  src/languages/golfscript/emit.ts
  src/languages/golfscript/golfscript.test.md
  src/languages/golfscript/index.ts
  src/languages/golfscript/plugins.ts
  src/languages/lua/emit.ts
  src/languages/lua/index.ts
  src/languages/lua/lua.test.md
  src/languages/nim/emit.ts
  src/languages/nim/index.ts
  src/languages/nim/nim.test.md
  src/languages/nim/plugins.ts
  src/languages/polygolf/emit.ts
  src/languages/python/emit.ts
  src/languages/python/index.ts
  src/languages/python/python.test.md
  src/languages/swift/emit.ts
  src/languages/swift/index.ts
  src/languages/swift/swift.test.md
  src/plugins/loops.test.md
  src/plugins/loops.ts
Labels: enhancement, high priority

#126 Ranges improvements
  src/IR/exprs.ts
  src/languages/golfscript/emit.ts
  src/languages/golfscript/index.ts
  src/languages/lua/emit.ts
  src/languages/lua/index.ts
  src/languages/lua/lua.test.md
  src/languages/nim/emit.ts
  src/languages/nim/index.ts
  src/languages/nim/nim.test.md
  src/languages/python/emit.ts
  src/languages/python/index.ts
  src/languages/python/python.test.md
  src/languages/swift/emit.ts
  src/languages/swift/index.ts
  src/plugins/loops.test.md
  src/plugins/loops.ts
  src/plugins/ops.ts
Labels: bug, enhancement, high priority

#148 Add and implement bit shift left and right opcodes
  README.md
  src/IR/opcodes.ts
  src/common/getType.test.ts
  src/common/getType.ts
  src/frontend/lexer.ts
  src/frontend/parse.ts
  src/languages/golfscript/index.ts
  src/languages/lua/index.ts
  src/languages/lua/lua.test.md
  src/languages/nim/index.ts
  src/languages/polygolf/emit.ts
  src/languages/python/index.ts
  src/languages/swift/index.ts
Labels: enhancement

#71 Text subtypes
  src/IR/opcodes.ts
  src/IR/types.ts
  src/common/applyLanguage.ts
  src/common/getType.test.ts
  src/common/getType.ts
  src/frontend/lexer.ts
  src/frontend/parse.test.ts
  src/frontend/parse.ts
  src/languages/golfscript/index.ts
  src/languages/lua/index.ts
  src/languages/lua/lua.test.md
  src/languages/nim/index.ts
  src/languages/python/index.ts
  src/languages/python/python.test.md
  src/languages/swift/index.ts
  src/plugins/hashing.test.md
  src/plugins/packing.ts
  src/plugins/textOps.test.md
  src/plugins/textOps.ts
Labels: enhancement, high priority, architecture

#149 Update docs
  README.md
  docs/architecture.md
  src/programs/code.golf-default.test.md
Labels: documentation

#73 Fix #38
  src/frontend/grammar.ne
  src/frontend/parse.test.ts
Labels: bug
